name: style checks

on: [pull_request]

jobs:
  prettier:
    name: prettier has been run on compatible files
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: check that modified files are prettier
        run: npx prettier .
  eslint:
    name: frontend linting
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies ui-src
        working-directory: services/ui-src
        run: yarn install
      - name: run eslint ui-src
        working-directory: services/ui-src
        run: npx eslint .
      - name: install dependencies app-api
        working-directory: services/app-api
        run: yarn install
      - name: run eslint app-api
        working-directory: services/app-api
        run: npx eslint .